workspace:
  base: /back
  path: src/github.com/Howard21432134/backend
pipeline:
  build:
    image: maven:3.6.0-jdk-8-alpine
    commands:
      - mvn install
      - mvn clean package
  publish:
    image: plugins/docker
    repo: 978118325/backend
    tags: ["latest", "v2"]
    secrets: [ docker_username, docker_password ]
    dockerfile: Dockerfile